apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification
        image: <ACCOUNT-ID>.dkr.ecr.<AWS-REGION>.amazonaws.com/notification-service:latest
        ports:
        - containerPort: 5002
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: notification-config
              key: ENVIRONMENT
        - name: EMAIL_SMTP_SERVER
          valueFrom:
            configMapKeyRef:
              name: notification-config
              key: EMAIL_SMTP_SERVER
        - name: SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: notification-config
              key: SERVICE_NAME
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: notification-secret
              key: SMTP_USERNAME
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: notification-secret
              key: SMTP_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
  - protocol: TCP
    port: 80
