apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-scheduling-deployment
  labels:
    app: appointment-scheduling-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-scheduling-service
  template:
    metadata:
      labels:
        app: appointment-scheduling-service
    spec:
      containers:
      - name: appointment-scheduling
        image: appointment-scheduling-service:latest
        ports:
        - containerPort: 5001
